server:
  port: 9900


myConfig:
  myObject:
    myName: zhangsan
    myAge: 18

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

spring:
  profiles:
    #运行的环境
    active: test
  application:
    name: demo
  datasource:
    url: jdbc:mysql://${mallchat.mysql.ip}:${mallchat.mysql.port}/${mallchat.mysql.db}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: ${mallchat.mysql.username}
    password: ${mallchat.mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      max-lifetime: 30000   #不能小于30秒，否则默认回到1800秒
      connection-test-query: SELECT 1
  redis:
    # Redis服务器地址
    host: ${mallchat.redis.host}
    # Redis服务器端口号
    port: ${mallchat.redis.port}
    # 使用的数据库索引，默认是0
    database: 0
    # 连接超时时间
    timeout: 1800000
     #设置密码
    #password: ${mallchat.redis.password}
    lettuce:
      pool:
        # 最大阻塞等待时间，负数表示没有限制
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 5
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中最大连接数，负数表示没有限制
        max-active: 20
  rabbitmq:
    host: ${mallchat.rabbitmq.host}
    port: ${mallchat.rabbitmq.port}
    username: ${mallchat.rabbitmq.username}
    password: ${mallchat.rabbitmq.password}
    virtual-host: ${mallchat.rabbitmq.virtualhost}
# 先完成对象的属性赋值工作，然后再生成了代理对象 所以报错 not use the final version of the bean
# 需要将对象的创建进行前置操作， 需要在对象的属性赋值之前必须要唯一性的确定出原始对象还是代理对象 三级缓存中




